import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const isWatch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */",
  },
  bundle: true,
  entryPoints: ["main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  logLevel: "info",
  outfile: "main.js",
  platform: "browser",
  sourcemap: "inline",
  target: "es2022",
  treeShaking: true,
});

if (isWatch) {
  await context.watch();
  console.log("Watching for changes...");
} else {
  await context.rebuild();
  await context.dispose();
}
